//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leaders_RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contrato()
        {
            this.Referido1 = new HashSet<Referido>();
            this.Referido2 = new HashSet<Referido>();
        }
    
        public int ContratoId { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Pais { get; set; }
        public string Ciudad { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string Licencia { get; set; }
        public Nullable<int> FK_Vehiculo { get; set; }
        public string Clase { get; set; }
        public string Combustible_Salida { get; set; }
        public string Combustible_Entrada { get; set; }
        public string Kilometraje_Salida { get; set; }
        public string Kilometraje_Entrada { get; set; }
        public Nullable<int> Cantidad_Dias { get; set; }
        public Nullable<int> Dias_Extras { get; set; }
        public Nullable<decimal> Descuento_Comision { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string FormaPago { get; set; }
        public string Contrato1 { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio { get; set; }
        public Nullable<System.DateTime> Fecha_Cierre { get; set; }
        public string Condiciones { get; set; }
        public string Tipo_Renta { get; set; }
        public string Estatus { get; set; }
        public string Referido { get; set; }
    
        public virtual Vehiculo Vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Referido> Referido1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Referido> Referido2 { get; set; }
   
    }
    public enum clase
        {
            ECAR,
            CCAR,
            ICAR,
            CFAR,
            IFAR,
            FFAR,
            FPMR,
            FVAR
        }
}
