//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leaders_RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referido
    {
        public int ReferidoId { get; set; }
        public Nullable<int> FK_Referido { get; set; }
        public Nullable<int> FK_NumeroContrato { get; set; }
        public string Comision { get; set; }
        public string Estatus { get; set; }
    
        public virtual contrato contrato { get; set; }
        public virtual contrato contrato1 { get; set; }
    }
}
